# Generated by Django 4.2.6 on 2023-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeuser',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
