# Generated by Django 4.2.6 on 2023-10-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_groupeuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.groupeuser'),
        ),
    ]
