# Generated by Django 4.2.6 on 2023-10-14 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companys', '0002_company_address_company_city_company_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': (), 'permissions': (('view_company', 'Can view company'), ('add_company', 'Can add company'), ('change_company', 'Can change company'), ('delete_company', 'Can delete company')), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'name'], name='company_user_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='company_user_name_uc'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
